name: home
description: Home modules of Car Crew.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.2.3 <4.0.0"
  flutter: ">=3.3.0"


dependencies:
  car_crew_ui_kit:
    path: ../../packages/car_crew_ui_kit
  core:
    path: ../../core
  dependencies:
    path: ../../shared/dependencies
  flutter:
    sdk: flutter
  l10n:
    path: ../../shared/l10n


dev_dependencies:
  auto_route_generator: ^9.3.1
  # bloc_test: ^10.0.0
  build_runner: ^2.4.14
  flutter_test:
    sdk: flutter
  freezed: ^2.5.8
  injectable_generator: ^2.7.0
  json_serializable: ^6.9.3
  mocktail: ^1.0.4
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true
