targets:
  $default:
    builders:
      auto_route_generator:auto_route_generator:
        generate_for:
          include:
            - lib/router/wrappers/**.dart
            - lib/presentation/ui/pages/**.dart
      auto_route_generator:auto_router_generator:
        generate_for:
          include:
            - lib/router/**.dart
