name: car_crew
description: "A Flutter app project of Car Crew"
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 0.0.1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  config:
    path: ../../shared/config
  core:
    path: ../../core
    
  cupertino_icons: ^1.0.8
  dependencies:
    path: ../../shared/dependencies
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.4
  home:
    path: ../../features/home
  l10n:
    path: ../../shared/l10n
  car_crew_ui_kit:
    path: ../../packages/car_crew_ui_kit

dev_dependencies:
  auto_route_generator: ^9.3.1
  build_runner: ^2.4.14
  change_app_package_name: ^1.4.0
  flutter_flavorizr: ^2.2.3
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.7.0
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true
