name: car_crew_workspace
description: "A monorepo Flutter project with Melos for Car Crew"

version: 0.0.1

environment:
  sdk: ">=3.2.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^5.0.0
  melos: ^6.3.2
  very_good_analysis: ^7.0.0
