name: core
description: >
  Core module package for Car Crew.
  Contains essential functionalities, utilities,
  and shared components for the application.
version: 0.0.1
publish_to: "none" # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=3.2.3 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  config:
    path: ../shared/config
  connectivity_plus: ^6.1.2
  dependencies:
    path: ../shared/dependencies
  device_info_plus: ^11.1.1
  
  dio: ^5.7.0
  dio_cache_interceptor: ^3.5.1
  dio_cache_interceptor_hive_store: ^4.0.0
  dio_smart_retry: ^7.0.1
  
  
  
  flutter:
    sdk: flutter
  l10n:
    path: ../shared/l10n
  logger: ^2.5.0
  package_info_plus: ^8.1.3
  path_provider: ^2.1.5
  permission_handler: ^11.3.1
  url_launcher: ^6.3.1
  version: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.14
  flutter_lints: ^5.0.0
  freezed: ^2.5.8
  injectable_generator: ^2.7.0
  json_serializable: ^6.9.3
  mocktail: ^1.0.4
  very_good_analysis: ^7.0.0
