name: config
description: "Configuration package for Car Crew. Manages environment-specific settings, API endpoints, and other configuration parameters across different build flavors (development, staging, production)."
version: 0.0.1
publish_to: "none" # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=3.2.3 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  envied: ^1.1.0
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.4.14
  envied_generator: ^1.1.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^7.0.0
