name: l10n
description: "A comprehensive internationalization package providing translation and localization support for Car Crew. This package manages multi-language support, facilitates easy integration of new languages, and ensures a consistent user experience across different locales."
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.2.3 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  slang: ^4.4.1
  slang_flutter: ^4.4.0

dev_dependencies:
  build_runner: ^2.4.14
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  slang_build_runner: ^4.4.0
  very_good_analysis: ^7.0.0
